# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\EquipWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(604, 266)
        self.data_view = QtWidgets.QTextBrowser(Dialog)
        self.data_view.setGeometry(QtCore.QRect(290, 10, 301, 241))
        self.data_view.setObjectName("data_view")
        self.time_moment_select = QtWidgets.QComboBox(Dialog)
        self.time_moment_select.setGeometry(QtCore.QRect(10, 50, 271, 31))
        self.time_moment_select.setEditable(True)
        self.time_moment_select.setObjectName("time_moment_select")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 211, 16))
        self.label_2.setObjectName("label_2")
        self.freq_select = QtWidgets.QDoubleSpinBox(Dialog)
        self.freq_select.setGeometry(QtCore.QRect(10, 190, 191, 22))
        self.freq_select.setDecimals(4)
        self.freq_select.setMinimum(433.0)
        self.freq_select.setMaximum(435.0)
        self.freq_select.setSingleStep(0.0001)
        self.freq_select.setObjectName("freq_select")
        self.ch_freq = QtWidgets.QPushButton(Dialog)
        self.ch_freq.setGeometry(QtCore.QRect(10, 230, 93, 28))
        self.ch_freq.setObjectName("ch_freq")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Equipments control"))
        self.label.setText(_translate("Dialog", "Выбрать момент времени"))
        self.label_2.setText(_translate("Dialog", "Сменить  частоту сканирования"))
        self.ch_freq.setText(_translate("Dialog", "Сменить"))

