# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.transive = QtWidgets.QPushButton(self.centralwidget)
        self.transive.setGeometry(QtCore.QRect(350, 20, 281, 41))
        self.transive.setObjectName("transive")
        self.Actions = QtWidgets.QButtonGroup(MainWindow)
        self.Actions.setObjectName("Actions")
        self.Actions.addButton(self.transive)
        self.equip_check = QtWidgets.QPushButton(self.centralwidget)
        self.equip_check.setGeometry(QtCore.QRect(350, 70, 281, 41))
        self.equip_check.setObjectName("equip_check")
        self.Actions.addButton(self.equip_check)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 320, 231, 16))
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 120, 281, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Actions.addButton(self.pushButton_4)
        self.time_select = QtWidgets.QComboBox(self.centralwidget)
        self.time_select.setGeometry(QtCore.QRect(10, 350, 231, 22))
        self.time_select.setObjectName("time_select")
        self.moment_data = QtWidgets.QTextEdit(self.centralwidget)
        self.moment_data.setGeometry(QtCore.QRect(350, 240, 331, 201))
        self.moment_data.setObjectName("moment_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.transive.setText(_translate("MainWindow", "Запрос на отправку записаных данных"))
        self.equip_check.setText(_translate("MainWindow", "Контроль оборудования"))
        self.label.setText(_translate("MainWindow", "Данные в момент времени:"))
        self.pushButton_4.setText(_translate("MainWindow", "Настройки"))
