# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\RtWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(642, 337)
        self.data_view = QtWidgets.QTextBrowser(Dialog)
        self.data_view.setGeometry(QtCore.QRect(10, 10, 621, 251))
        self.data_view.setObjectName("data_view")
        self.save2csv = QtWidgets.QPushButton(Dialog)
        self.save2csv.setGeometry(QtCore.QRect(10, 280, 581, 41))
        self.save2csv.setObjectName("save2csv")
        self.delim = QtWidgets.QLineEdit(Dialog)
        self.delim.setGeometry(QtCore.QRect(600, 290, 31, 31))
        self.delim.setObjectName("delim")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save2csv.setText(_translate("Dialog", "Сохранить в csv файл"))
        self.delim.setText(_translate("Dialog", ";"))
